########################
# CONFIGS FOR RABBITMQ #
########################

RABBITMQ_HOST = '34.145.90.213'
RABBITMQ_PORT = 5672
RABBITMQ_VHOST = '/'
RABBITMQ_LOGIN = 'user'
RABBITMQ_PASSWORD = '12JqEf2T5Fn6QZCF'

RABBITMQ_URL = f'''amqp://{RABBITMQ_LOGIN}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}'''

#####################
# CONFIGS FOR REDIS #
#####################

REDIS_HOST = '35.247.62.69'
REDIS_PORT = 6379
REDIS_USERNAME = 'user'
REDIS_PASSWORD = 'LYWxyNDJSg7h'

REDIS_URL = f'''redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}'''

##############################
# CONFIGS FOR POSTGRESQL_SON #
##############################

POSTGRES_HOST_SON = '10.63.16.42'
POSTGRES_PORT_SON = 5432
POSTGRESS_DB_SON = 'ru-video-products'
POSTGRES_LOGIN_SON = 'postgres'
POSTGRES_PASSWORD_SON = 'pLD30qaJr7tc5rlk'

POSTGRES_URL_SON = f'postgresql://{POSTGRES_LOGIN_SON}:{POSTGRES_PASSWORD_SON}' \
                     f'@{POSTGRES_HOST_SON}:{POSTGRES_PORT_SON}/{POSTGRESS_DB_SON}'

#################################
# CONFIGS FOR POSTGRESQL_FATHER #
#################################

POSTGRES_HOST_FATHER = '10.63.16.34'
POSTGRES_PORT_FATHER = 5432
POSTGRESS_DB_FATHER = 'oxicore-video-products'
POSTGRES_LOGIN_FATHER = 'postgres'
POSTGRES_PASSWORD_FATHER = 'zPc0HxpCfHxpNu0D'

POSTGRES_URL_FATHER = f'postgresql://{POSTGRES_LOGIN_FATHER}:{POSTGRES_PASSWORD_FATHER}' \
                      f'@{POSTGRES_HOST_FATHER}:{POSTGRES_PORT_FATHER}/{POSTGRESS_DB_FATHER}'
